/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...404]': RouteRecordInfo<
      '/[...404]',
      '/:404(.*)',
      { 404: ParamValue<true> },
      { 404: ParamValue<false> },
      | never
    >,
    '/bar': RouteRecordInfo<
      '/bar',
      '/bar',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/media': RouteRecordInfo<
      '/media',
      '/media',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/notes': RouteRecordInfo<
      '/notes',
      '/notes',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/photos': RouteRecordInfo<
      '/photos',
      '/photos',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/': RouteRecordInfo<
      '/posts/',
      '/posts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/APP-Packet Capture Issues': RouteRecordInfo<
      '/posts/APP-Packet Capture Issues',
      '/posts/APP-Packet Capture Issues',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Docker-Commands': RouteRecordInfo<
      '/posts/Docker-Commands',
      '/posts/Docker-Commands',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Docker-Container Data Volume': RouteRecordInfo<
      '/posts/Docker-Container Data Volume',
      '/posts/Docker-Container Data Volume',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Docker-DockerFile': RouteRecordInfo<
      '/posts/Docker-DockerFile',
      '/posts/Docker-DockerFile',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Docker-Image Principle': RouteRecordInfo<
      '/posts/Docker-Image Principle',
      '/posts/Docker-Image Principle',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Docker-Network': RouteRecordInfo<
      '/posts/Docker-Network',
      '/posts/Docker-Network',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/HTTP&HTTPS': RouteRecordInfo<
      '/posts/HTTP&HTTPS',
      '/posts/HTTP&HTTPS',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Information-Gathering': RouteRecordInfo<
      '/posts/Information-Gathering',
      '/posts/Information-Gathering',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/JWT': RouteRecordInfo<
      '/posts/JWT',
      '/posts/JWT',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Kali-install-drozer': RouteRecordInfo<
      '/posts/Kali-install-drozer',
      '/posts/Kali-install-drozer',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Koishi-NapCat-QQBot': RouteRecordInfo<
      '/posts/Koishi-NapCat-QQBot',
      '/posts/Koishi-NapCat-QQBot',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/TargetMachine-Linux-1': RouteRecordInfo<
      '/posts/TargetMachine-Linux-1',
      '/posts/TargetMachine-Linux-1',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/TargetMachine-Linux-2': RouteRecordInfo<
      '/posts/TargetMachine-Linux-2',
      '/posts/TargetMachine-Linux-2',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/TargetMachine-Windows-Web1': RouteRecordInfo<
      '/posts/TargetMachine-Windows-Web1',
      '/posts/TargetMachine-Windows-Web1',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/TargetMachine-Windows-Web2': RouteRecordInfo<
      '/posts/TargetMachine-Windows-Web2',
      '/posts/TargetMachine-Windows-Web2',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/TargetMachine-Windows-Web3': RouteRecordInfo<
      '/posts/TargetMachine-Windows-Web3',
      '/posts/TargetMachine-Windows-Web3',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/XXE': RouteRecordInfo<
      '/posts/XXE',
      '/posts/XXE',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/XXE-lab': RouteRecordInfo<
      '/posts/XXE-lab',
      '/posts/XXE-lab',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/use': RouteRecordInfo<
      '/use',
      '/use',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'pages/index.md': {
      routes:
        | '/'
      views:
        | never
    }
    'pages/[...404].md': {
      routes:
        | '/[...404]'
      views:
        | never
    }
    'pages/bar.md': {
      routes:
        | '/bar'
      views:
        | never
    }
    'pages/media.md': {
      routes:
        | '/media'
      views:
        | never
    }
    'pages/notes.md': {
      routes:
        | '/notes'
      views:
        | never
    }
    'pages/photos.md': {
      routes:
        | '/photos'
      views:
        | never
    }
    'pages/posts/index.md': {
      routes:
        | '/posts/'
      views:
        | never
    }
    'pages/posts/APP-Packet Capture Issues.md': {
      routes:
        | '/posts/APP-Packet Capture Issues'
      views:
        | never
    }
    'pages/posts/Docker-Commands.md': {
      routes:
        | '/posts/Docker-Commands'
      views:
        | never
    }
    'pages/posts/Docker-Container Data Volume.md': {
      routes:
        | '/posts/Docker-Container Data Volume'
      views:
        | never
    }
    'pages/posts/Docker-DockerFile.md': {
      routes:
        | '/posts/Docker-DockerFile'
      views:
        | never
    }
    'pages/posts/Docker-Image Principle.md': {
      routes:
        | '/posts/Docker-Image Principle'
      views:
        | never
    }
    'pages/posts/Docker-Network.md': {
      routes:
        | '/posts/Docker-Network'
      views:
        | never
    }
    'pages/posts/HTTP&HTTPS.md': {
      routes:
        | '/posts/HTTP&HTTPS'
      views:
        | never
    }
    'pages/posts/Information-Gathering.md': {
      routes:
        | '/posts/Information-Gathering'
      views:
        | never
    }
    'pages/posts/JWT.md': {
      routes:
        | '/posts/JWT'
      views:
        | never
    }
    'pages/posts/Kali-install-drozer.md': {
      routes:
        | '/posts/Kali-install-drozer'
      views:
        | never
    }
    'pages/posts/Koishi-NapCat-QQBot.md': {
      routes:
        | '/posts/Koishi-NapCat-QQBot'
      views:
        | never
    }
    'pages/posts/TargetMachine-Linux-1.md': {
      routes:
        | '/posts/TargetMachine-Linux-1'
      views:
        | never
    }
    'pages/posts/TargetMachine-Linux-2.md': {
      routes:
        | '/posts/TargetMachine-Linux-2'
      views:
        | never
    }
    'pages/posts/TargetMachine-Windows-Web1.md': {
      routes:
        | '/posts/TargetMachine-Windows-Web1'
      views:
        | never
    }
    'pages/posts/TargetMachine-Windows-Web2.md': {
      routes:
        | '/posts/TargetMachine-Windows-Web2'
      views:
        | never
    }
    'pages/posts/TargetMachine-Windows-Web3.md': {
      routes:
        | '/posts/TargetMachine-Windows-Web3'
      views:
        | never
    }
    'pages/posts/XXE.md': {
      routes:
        | '/posts/XXE'
      views:
        | never
    }
    'pages/posts/XXE-lab.md': {
      routes:
        | '/posts/XXE-lab'
      views:
        | never
    }
    'pages/use.md': {
      routes:
        | '/use'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
